[features]
seeds = false
skip-lint = false
[programs.localnet]
gopulse = "3tMVmtunb5Z73Gqo6EKCKCzCMJkTA5JkALdF6hLjdWWn"
[programs.devnet]
gopulse = "3tMVmtunb5Z73Gqo6EKCKCzCMJkTA5JkALdF6hLjdWWn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/tomdevito27/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
